"""empty message

Revision ID: f5b448c11848
Revises: e6655174a553
Create Date: 2026-04-18 14:34:24.248250

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'f5b448c11848'
down_revision: Union[str, Sequence[str], None] = 'e6655174a553'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbank_shares',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('figi', sa.String(length=64), nullable=False),
    sa.Column('ticker', sa.String(length=32), nullable=True),
    sa.Column('class_code', sa.String(length=32), nullable=True),
    sa.Column('isin', sa.String(length=32), nullable=True),
    sa.Column('uid', sa.String(length=64), nullable=True),
    sa.Column('position_uid', sa.String(length=64), nullable=True),
    sa.Column('instrument_name', sa.String(length=512), nullable=True),
    sa.Column('currency', sa.String(length=16), nullable=True),
    sa.Column('exchange', sa.String(length=64), nullable=True),
    sa.Column('country_of_risk', sa.String(length=16), nullable=True),
    sa.Column('buy_available', sa.Boolean(), nullable=True),
    sa.Column('sell_available', sa.Boolean(), nullable=True),
    sa.Column('for_iis', sa.Boolean(), nullable=True),
    sa.Column('for_qual_investor', sa.Boolean(), nullable=True),
    sa.Column('api_trade_available', sa.Boolean(), nullable=True),
    sa.Column('short_enabled', sa.Boolean(), nullable=True),
    sa.Column('otc_flag', sa.Boolean(), nullable=True),
    sa.Column('real_exchange', sa.String(length=64), nullable=True),
    sa.Column('instrument_status', sa.String(length=64), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('instrument_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tbank_shares_figi'), 'tbank_shares', ['figi'], unique=True)
    op.create_index(op.f('ix_tbank_shares_isin'), 'tbank_shares', ['isin'], unique=False)
    op.create_index(op.f('ix_tbank_shares_ticker'), 'tbank_shares', ['ticker'], unique=False)
    op.create_index(op.f('ix_tbank_shares_uid'), 'tbank_shares', ['uid'], unique=False)
    op.create_table('tbank_share_prices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('share_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=20, scale=9), nullable=False),
    sa.Column('captured_at_msk', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['share_id'], ['tbank_shares.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tbank_share_prices_captured_at_msk'), 'tbank_share_prices', ['captured_at_msk'], unique=False)
    op.create_index(op.f('ix_tbank_share_prices_share_id'), 'tbank_share_prices', ['share_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tbank_share_prices_share_id'), table_name='tbank_share_prices')
    op.drop_index(op.f('ix_tbank_share_prices_captured_at_msk'), table_name='tbank_share_prices')
    op.drop_table('tbank_share_prices')
    op.drop_index(op.f('ix_tbank_shares_uid'), table_name='tbank_shares')
    op.drop_index(op.f('ix_tbank_shares_ticker'), table_name='tbank_shares')
    op.drop_index(op.f('ix_tbank_shares_isin'), table_name='tbank_shares')
    op.drop_index(op.f('ix_tbank_shares_figi'), table_name='tbank_shares')
    op.drop_table('tbank_shares')
    # ### end Alembic commands ###
