"""empty message

Revision ID: fcc872d62fd2
Revises: f5b448c11848
Create Date: 2026-04-18 16:01:50.852441

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = 'fcc872d62fd2'
down_revision: Union[str, Sequence[str], None] = 'f5b448c11848'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tbank_share_prices', sa.Column('trading_open', sa.Boolean(), server_default='true', nullable=False))
    op.drop_index(op.f('ix_tbank_shares_uid'), table_name='tbank_shares')
    op.drop_column('tbank_shares', 'for_iis')
    op.drop_column('tbank_shares', 'instrument_status')
    op.drop_column('tbank_shares', 'uid')
    op.drop_column('tbank_shares', 'position_uid')
    op.drop_column('tbank_shares', 'for_qual_investor')
    op.drop_column('tbank_shares', 'otc_flag')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tbank_shares', sa.Column('otc_flag', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('tbank_shares', sa.Column('for_qual_investor', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('tbank_shares', sa.Column('position_uid', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.add_column('tbank_shares', sa.Column('uid', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.add_column('tbank_shares', sa.Column('instrument_status', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.add_column('tbank_shares', sa.Column('for_iis', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_tbank_shares_uid'), 'tbank_shares', ['uid'], unique=False)
    op.drop_column('tbank_share_prices', 'trading_open')
    # ### end Alembic commands ###
